server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://115.159.117.170:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: ding1998713
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/**.xml
